/**
    This file was generated by 'ci/util/generate_img.py'
*/
package ch.bailu.aat.resource;


import ch.bailu.aat.R;

public final class Images {
    public static int get(String name) {
        switch(name) {
            case "dialog_question":
                return R.drawable.dialog_question;
            case "document_save_as_inverse":
                return R.drawable.document_save_as_inverse;
            case "edit_clear_all_inverse":
                return R.drawable.edit_clear_all_inverse;
            case "edit_find":
                return R.drawable.edit_find;
            case "edit_redo":
                return R.drawable.edit_redo;
            case "edit_select_all_inverse":
                return R.drawable.edit_select_all_inverse;
            case "edit_undo":
                return R.drawable.edit_undo;
            case "edit_undo_inverse":
                return R.drawable.edit_undo_inverse;
            case "find_location":
                return R.drawable.find_location;
            case "folder_inverse":
                return R.drawable.folder_inverse;
            case "go_bottom":
                return R.drawable.go_bottom;
            case "go_bottom_inverse":
                return R.drawable.go_bottom_inverse;
            case "go_down":
                return R.drawable.go_down;
            case "go_down_inverse":
                return R.drawable.go_down_inverse;
            case "go_next_inverse":
                return R.drawable.go_next_inverse;
            case "go_previous_inverse":
                return R.drawable.go_previous_inverse;
            case "go_up":
                return R.drawable.go_up;
            case "go_up_inverse":
                return R.drawable.go_up_inverse;
            case "ic_launcher_background":
                return R.drawable.ic_launcher_background;
            case "ic_launcher_foreground":
                return R.drawable.ic_launcher_foreground;
            case "list_add":
                return R.drawable.list_add;
            case "list_remove":
                return R.drawable.list_remove;
            case "media_playback_pause_inverse":
                return R.drawable.media_playback_pause_inverse;
            case "media_playback_start_inverse":
                return R.drawable.media_playback_start_inverse;
            case "media_playback_stop_inverse":
                return R.drawable.media_playback_stop_inverse;
            case "open_menu":
                return R.drawable.open_menu;
            case "open_menu_inverse":
                return R.drawable.open_menu_inverse;
            case "open_menu_light":
                return R.drawable.open_menu_light;
            case "status":
                return R.drawable.status;
            case "user_trash":
                return R.drawable.user_trash;
            case "user_trash_inverse":
                return R.drawable.user_trash_inverse;
            case "view_grid":
                return R.drawable.view_grid;
            case "view_paged":
                return R.drawable.view_paged;
            case "view_paged_inverse":
                return R.drawable.view_paged_inverse;
            case "view_refresh":
                return R.drawable.view_refresh;
            case "view_refresh_inverse":
                return R.drawable.view_refresh_inverse;
            case "zoom_fit_best":
                return R.drawable.zoom_fit_best;
            case "zoom_in":
                return R.drawable.zoom_in;
            case "zoom_original":
                return R.drawable.zoom_original;
            case "zoom_original_inverse":
                return R.drawable.zoom_original_inverse;
            case "zoom_out":
                return R.drawable.zoom_out;
        }
        return 0;
    }
}
