#!/usr/bin/env python3
 
input_file = '../../aat-android/build/intermediates/runtime_symbol_list/release/R.txt'
output_file = '../../aat-lib/src/main/java/ch/bailu/aat_lib/resources/Images.java'

# Using readlines()
in_file = open(input_file, 'r')
out_file = open(output_file, 'w')

lines = in_file.readlines()
 
out_file.write('\n')
out_file.write('\n')
out_file.write('package ch.bailu.aat_lib.resources;\n') 
out_file.write('/**\n')
out_file.write('    This file was autogenerated by \'aat-lib/util/generate_img.py\'\n')
out_file.write('*/\n')
out_file.write('public final class Images {\n') 

 
count = 0
for line in lines:
    count += 1
    words = line.split()
    
    if (len(words) > 3):
        t = words[1]
        
        if words[1] == "drawable":
            name = words[2]
            number = words[3]
       
            print("{}: {}, {}".format(count, name, number))
            
            out_file.write('    public static int ' + name + '() { return ' + number + ';}\n')

        
out_file.write('}\n') 

        
   
in_file.close()
out_file.close()
