#!/bin/bash

# Transform scripts/about.html from html to an android resource string.
# To replace the 'about'-resource in 'res/values/strings.xml'
# usage:
#   bash scripts/aboutAsResource.bash scripts/about.html

echo '<string name="'$1'"><!-- This resource is autogenerated by '$0' -->'

cat $1 \
| sed 's/<!DOCTYPE html>//'\
| sed 's/<html>//'\
| sed 's/<li>/<br>-/'\
| sed 's/<\/li>//'\
| sed 's/<ul>//'\
| sed 's/<\/ul>//'\
| sed 's/<code>/<b>/'\
| sed 's/<\/code>/<\/b>/'\
| sed 's/<body>//'     \
| sed 's/<\/body>//'   \
| sed 's/</\&lt;/g' \
| sed 's/'\''/\\'\''/' 
echo '</string>'
