#!/bin/bash

# Transform scripts/about.html from html to an android resource string.
# To replace the 'about'-resource in 'res/values/strings.xml'
# usage:
#   bash scripts/aboutAsResource.bash scripts/about.html


cat $1 \
| sed 's/</\&lt;/g'       \
| sed 's/&lt;!DOCTYPE html>//'\
| sed 's/&lt;html>/<string name="resource_name"><!-- This resource is autogenerated by '$0' -->/'\
| sed 's/&lt;body>//'     \
| sed 's/&lt;\/body>//'   \
| sed 's/&lt;\/html>/<\/string>/' \
| sed 's/'\''/\\'\''/'


