#!/usr/bin/env python3

import sys
import xml.etree.ElementTree as ET


if (len(sys.argv) > 1):
    lang_path = sys.argv[1] + '/'
    class_name = 'Strings_' + sys.argv[1]
else:
    lang_path = ''
    class_name = 'Strings'
    

input_file = '../../app/src/main/res/values/' + lang_path + 'strings.xml'

java_header = """
package ch.bailu.aat_lib.resources;

/**
    This file is autogenerated by 'aat-awt/util/generate_strings.py'.
*/
"""
print(java_header)
print("public class " + class_name + " {")

root_node = ET.parse(input_file).getroot()

for tag in root_node.findall('string'):
    key = tag.get('name')
    value = tag.text
    
    print("    public String " + key + "() { return \"" + value + "\";}")
    
for array_tag in root_node.findall('string-array'):
    print("    public String[] " + array_tag.get('name') + "() {")
    print("        return new String[] {")
    
    for tag in array_tag.findall('item'):
        print("            \"" + tag.text + "\",")
    
    print("        };")
    print("    }")
        
    
    
print("}")
