

package ch.bailu.aat_lib.resources;
/**
    This file was autogenerated by 'aat-lib/util/generate_img.py'
*/
public final class Images {
    public static int dialog_question() { return 0x7f030000;}
    public static int document_save_as_inverse() { return 0x7f030001;}
    public static int edit_clear_all_inverse() { return 0x7f030002;}
    public static int edit_find() { return 0x7f030003;}
    public static int edit_redo() { return 0x7f030004;}
    public static int edit_select_all_inverse() { return 0x7f030005;}
    public static int edit_undo() { return 0x7f030006;}
    public static int edit_undo_inverse() { return 0x7f030007;}
    public static int find_location() { return 0x7f030008;}
    public static int folder_inverse() { return 0x7f030009;}
    public static int go_bottom() { return 0x7f03000a;}
    public static int go_bottom_inverse() { return 0x7f03000b;}
    public static int go_down() { return 0x7f03000c;}
    public static int go_down_inverse() { return 0x7f03000d;}
    public static int go_next_inverse() { return 0x7f03000e;}
    public static int go_previous_inverse() { return 0x7f03000f;}
    public static int go_up() { return 0x7f030010;}
    public static int go_up_inverse() { return 0x7f030011;}
    public static int ic_launcher_background() { return 0x7f030012;}
    public static int ic_launcher_foreground() { return 0x7f030013;}
    public static int list_add() { return 0x7f030014;}
    public static int list_remove() { return 0x7f030015;}
    public static int media_playback_pause_inverse() { return 0x7f030016;}
    public static int media_playback_start_inverse() { return 0x7f030017;}
    public static int media_playback_stop_inverse() { return 0x7f030018;}
    public static int open_menu() { return 0x7f030019;}
    public static int open_menu_inverse() { return 0x7f03001a;}
    public static int open_menu_light() { return 0x7f03001b;}
    public static int status() { return 0x7f03001c;}
    public static int user_trash() { return 0x7f03001d;}
    public static int user_trash_inverse() { return 0x7f03001e;}
    public static int view_grid() { return 0x7f03001f;}
    public static int view_paged() { return 0x7f030020;}
    public static int view_paged_inverse() { return 0x7f030021;}
    public static int view_refresh() { return 0x7f030022;}
    public static int view_refresh_inverse() { return 0x7f030023;}
    public static int zoom_fit_best() { return 0x7f030024;}
    public static int zoom_in() { return 0x7f030025;}
    public static int zoom_original() { return 0x7f030026;}
    public static int zoom_original_inverse() { return 0x7f030027;}
    public static int zoom_out() { return 0x7f030028;}
}
