package ch.bailu.aat_lib.resources;

/**
    This file was autogenerated by 'aat-lib/util/generate_strings.py'.
*/
public class Strings_nl extends Strings {
    @Override
    public String on() { return "Aan";}

    @Override
    public String off() { return "Uit";}

    @Override
    public String auto() { return "Auto";}

    @Override
    public String none() { return "Geen";}

    @Override
    public String enter() { return "Ingeven…";}

    @Override
    public String pick() { return "Kies (SAF)…";}

    @Override
    public String ok() { return "OK";}

    @Override
    public String cancel() { return "Annuleren";}

    @Override
    public String gps() { return "GPS";}

    @Override
    public String gps_wait() { return "…";}

    @Override
    public String gps_nogps() { return "Geen";}

    @Override
    public String gps_noaccess() { return "Geweigerd";}

    @Override
    public String tracker() { return "Tracker";}

    @Override
    public String tracker_start() { return "Start";}

    @Override
    public String tracker_pause() { return "Pauze";}

    @Override
    public String tracker_stop() { return "Stop";}

    @Override
    public String tracker_resume() { return "Hervatten";}

    @Override
    public String tracker_restore() { return "Herstel track";}

    @Override
    public String status_paused() { return "Gepauzeerd";}

    @Override
    public String status_autopaused() { return "A-pauze";}

    @Override
    public String intro_about() { return "Over";}

    @Override
    public String intro_readme() { return "LEESMIJ";}

    @Override
    public String intro_documentation() { return "Documentatie";}

    @Override
    public String intro_cockpit_a() { return "Cockpit A";}

    @Override
    public String intro_cockpit_b() { return "Cockpit B";}

    @Override
    public String intro_map() { return "Kaart";}

    @Override
    public String intro_nominatim() { return "Kaart zoeken";}

    @Override
    public String intro_overlay_list() { return "Overlay lijst";}

    @Override
    public String intro_list() { return "Track lijst";}

    @Override
    public String intro_external_list() { return "Externe bestanden";}

    @Override
    public String intro_settings() { return "Voorkeuren";}

    @Override
    public String label_summary() { return "Samenvatting";}

    @Override
    public String label_filter() { return "Filter";}

    @Override
    public String label_list() { return "Lijst";}

    @Override
    public String filter_geo() { return "Binnen grenzen";}

    @Override
    public String filter_date_start() { return "Start datum";}

    @Override
    public String filter_date_to() { return "Eind datum";}

    @Override
    public String query_overpass() { return "Overpass";}

    @Override
    public String query_features() { return "OSM Features";}

    @Override
    public String query_save_copy() { return "Slaag kopie op";}

    @Override
    public String p_general() { return "Algemeen";}

    @Override
    public String p_post_autopause() { return "Autopauze na proces";}

    @Override
    public String p_preset_slots() { return "Zichtbare presets";}

    @Override
    public String p_unit_title() { return "Eenheden";}

    @Override
    public String p_location_provider() { return "Locatie provider";}

    @Override
    public String p_location_gps() { return "Systeem GPS";}

    @Override
    public String p_location_mock() { return "Nagemaakte location";}

    @Override
    public String p_directory_data() { return "Data folder";}

    @Override
    public String p_cache_size() { return "Interne cachegrootte";}

    @Override
    public String p_fix_gps() { return "Fix GPS tijd";}

    @Override
    public String p_overlay() { return "Overlays";}

    @Override
    public String p_legend_fulldistance() { return "Continue afstand";}

    @Override
    public String p_preset() { return "Activiteit";}

    @Override
    public String p_met() { return "MET en naam";}

    @Override
    public String p_autopause() { return "Autopauze";}

    @Override
    public String p_tracker_autopause() { return "Stel de tracker in om te autopauzeren";}

    @Override
    public String p_weight_title() { return "Je gewicht in kg";}

    @Override
    public String p_backlight_title() { return "Backlight";}

    @Override
    public String p_backlight_off() { return "Systeemstandaard";}

    @Override
    public String p_backlight_on() { return "Hou aan";}

    @Override
    public String p_backlight_on_no_lock() { return "Hou aan (Ontgrendel lock screen))";}

    @Override
    public String p_system() { return "Systeem";}

    @Override
    public String p_tile_size() { return "Tegelgrootte";}

    @Override
    public String p_accuracy_filter() { return "Nauwkeurigheidsfilter";}

    @Override
    public String p_distance_filter() { return "Afstandsfilter";}

    @Override
    public String p_missing_trigger() { return "Ontbrekende trigger";}

    @Override
    public String p_map() { return "Kaart";}

    @Override
    public String p_mapsforge_directory() { return "Offline kaartenfolder";}

    @Override
    public String p_mapsforge_theme() { return "Offline kaarten thema";}

    @Override
    public String p_enable_cache() { return "Laat cache toe";}

    @Override
    public String p_directory_tiles() { return "Tegelcache folder";}

    @Override
    public String p_trim_cache() { return "Trim tegelcache";}

    @Override
    public String p_tiles() { return "Kaarttegels";}

    @Override
    public String p_trim_mode() { return "Trim mode";}

    @Override
    public String p_trim_size() { return "Trimgrootte";}

    @Override
    public String p_trim_age() { return "Trimleeftijd";}

    @Override
    public String p_trim_month() { return "Maand";}

    @Override
    public String p_trim_months() { return "Maanden";}

    @Override
    public String p_trim_year() { return "Jaar";}

    @Override
    public String p_trim_years() { return "Jaren";}

    @Override
    public String p_trim_days() { return "Dagen";}

    @Override
    public String p_trim_total() { return "Totaal";}

    @Override
    public String p_remove_all() { return "Leeg de volledige cache";}

    @Override
    public String p_remove_all_in() { return "Leeg de volledige cache in";}

    @Override
    public String p_remove_old() { return "Verwijder oude tegels";}

    @Override
    public String p_remove_old_in() { return "Verwijder oude tegels in";}

    @Override
    public String file_reload() { return "Herlaad preview";}

    @Override
    public String file_delete() { return "Delete bestand";}

    @Override
    public String file_rename() { return "Hernoem bestand";}

    @Override
    public String file_overlay() { return "Gebruik als overlay";}

    @Override
    public String file_mock() { return "Gebruik voor namaaklokatie";}

    @Override
    public String file_delete_ask() { return "Verwijder bestand?";}

    @Override
    public String file_send() { return "Verstuur…";}

    @Override
    public String file_view() { return "Bekijk/Bewerk…";}

    @Override
    public String file_copy() { return "Kopieer naar…";}

    @Override
    public String file_exists() { return "\u0020bestaat al!";}

    @Override
    public String file_is_writeable() { return "\u0020is schrijfbaar.";}

    @Override
    public String file_is_writeonly() { return "\u0020is enkel schrijfbaar.";}

    @Override
    public String file_is_readonly() { return "\u0020is enkel leesbaar.";}

    @Override
    public String file_is_missing() { return "\u0020bestaat niet.";}

    @Override
    public String file_is_denied() { return "\u0020niet toegankelijk.";}

    @Override
    public String location_title() { return "Centreer locatie";}

    @Override
    public String location_view() { return "Bekijk locatie…";}

    @Override
    public String location_send() { return "Verstuur locatie…";}

    @Override
    public String clipboard_copy() { return "\u21d2 Clipboard";}

    @Override
    public String clipboard_paste() { return "\u21d0 Clipboard";}

    @Override
    public String dialog_yes() { return "Ja";}

    @Override
    public String dialog_no() { return "Nee";}

    @Override
    public String dialog_cancel() { return "Annuleer";}

    @Override
    public String dialog_discard() { return "Gooi weg";}

    @Override
    public String dialog_save() { return "Sla op";}

    @Override
    public String dialog_modified() { return "File is gewijzigd.";}

    @Override
    public String d_longitude() { return "Lengtegraad";}

    @Override
    public String d_latitude() { return "Breedtegraad";}

    @Override
    public String d_name() { return "Naam";}

    @Override
    public String d_accuracy() { return "Nauwkeurigheid";}

    @Override
    public String d_enddate() { return "Einde";}

    @Override
    public String d_startdate() { return "Start";}

    @Override
    public String d_acceleration() { return "Versnelling";}

    @Override
    public String d_bearing() { return "Richting";}

    @Override
    public String d_path() { return "Pad";}

    @Override
    public String d_state() { return "Staat";}

    @Override
    public String d_size() { return "Grootte";}

    @Override
    public String d_ascend() { return "Klim";}

    @Override
    public String d_descend() { return "Afdaling";}

    @Override
    public String d_slope() { return "Helling";}

    @Override
    public String pause() { return "Pauzeer";}

    @Override
    public String pause_ap() { return "Pauzeer (met autopause)";}

    @Override
    public String speed() { return "Snelheid";}

    @Override
    public String average() { return "Gemiddeld";}

    @Override
    public String average_ap() { return "Gemiddeld (zonder pauzes)";}

    @Override
    public String maximum() { return "Maximum";}

    @Override
    public String distance() { return "Afstand";}

    @Override
    public String altitude() { return "Hoogte";}

    @Override
    public String time() { return "Totale tijd";}

    @Override
    public String time_ap() { return "Totale tijd (zonder pauzes)";}

    @Override
    public String calories() { return "Calorieën";}

    @Override
    public String name() { return "Naam";}

    @Override
    public String tt_edit_add() { return "Voeg een punt toe met de locatie waarop de kaart gecentreerd is.";}

    @Override
    public String tt_edit_remove() { return "Verwijder geselecteerd punt.";}

    @Override
    public String tt_edit_up() { return "Verschuif punt eentje omhoog in de volgorde.";}

    @Override
    public String tt_edit_down() { return "Verschuif punt eentje omlaag in de volgorde.";}

    @Override
    public String tt_edit_redo() { return "Hermaak de laatste ongedane actie.";}

    @Override
    public String tt_edit_undo() { return "Hermaak de laatste actie.";}

    @Override
    public String tt_info_grid() { return "Wissel tussen roostermodes.";}

    @Override
    public String tt_info_legend() { return "Wissel tussen tracklegendemodes.";}

    @Override
    public String tt_info_nominatim() { return "Zoek met OSM-Nominatim.";}

    @Override
    public String tt_info_reload() { return "Herlaad zichtbare tegels.";}

    @Override
    public String tt_info_location() { return "Importeer/exporteer de centrumlocatie.";}

    @Override
    public String tt_map_zoomin() { return "Zoom in op de kaart.";}

    @Override
    public String tt_map_zoomout() { return "Zoom uit op de kaart.";}

    @Override
    public String tt_map_home() { return "Zet het centrum van de kaart vast op je huidige bekende locatie.";}

    @Override
    public String tt_map_frame() { return "Wissel tussen GPX-Overlays en frame ze.";}

    @Override
    public String tt_nominatim_query() { return "Start met zoeken.";}

    @Override
    public String tt_nominatim_clear() { return "Verwijder lijnen in de zoektext.";}

    @Override
    public String tt_cockpit_a() { return "Fullscreen";}

    @Override
    public String tt_cockpit_b() { return "Splitscreen";}

    @Override
    public String tt_menu_file() { return "Toon bestandsoperatie-menu.";}

    @Override
    public String tt_p_preset_slots() { return "Aantal folders en de presets die je wil gebruiken om tracks te organizeren";}

    @Override
    public String tt_p_distance_filter() { return "Enkel een GPS sample loggen indien het zich op een minimale afstand bevindt van de vorige sample.";}

    @Override
    public String tt_p_accuracy_filter() { return "Enkel een GPS sample loggen indien het minimale nauwkeurigheid heeft.";}

    @Override
    public String tt_p_missing_trigger() { return "Zet tracker op autopauze indien het GPS signaal voor een bepaalde periode onderbroken is.";}

    @Override
    public String error_integer() { return "Verkeerde input, enkel gehele getallen zijn toegestaan.\n\"%s\"";}

    @Override
    public String error_integer_positive() { return "Gewicht moet tussen 1 en 999 zijn.";}

    @Override
    public String error_long() { return "Verkeerde input, enkel getallen zijn toegestaan.\n\"%s\"";}

    @Override
    public String error_met() { return "Eerste Getal moet tussen 0.0 en 20.0 zijn, gevolgd door een spatie.";}

    @Override
    public String[] p_unit_list() {
        return new String[] {
            "Metrisch (km, km/h)",
            "Imperiaal (mi, mph)",
            "Nautisch (nm, kn)",
            "Internationaal Stelsel van Eenheden ",
        };
    }

    @Override
    public String[] p_met_list() {
        return new String[] {
            " 6.8 fietsen, vrije tijd, gematigde inspanning",
            " 8.5 fietsen, berg, algemeen",
            " 7.0 joggen, algemeen",
            " 6.0 wandelen, cross country",
            " 2.0 test",
            "14.0 fietsen, berg, bergop",
            "16.0 fietsen, berg, competitief",
            " 5.8 fietsen, vrije tijd, lichte inspanning",
            "10.0 fietsen, racen of vrije tijd, veel inspanning",
            " 6.0 lopen, 4 mph (13 min/mile)",
            " 9.0 lopen, 5.2 mph (11.5 min/mile)",
            " 9.8 lopen, 6 mph (10 min/mile)",
            " 9.0 lopen, cross country",
            "10.0 lopen, op een piste, team oefening",
            " 8.0 lopen, training, een rolstoel of kinderwagen duwend",
            "13.3 lopen, marathon",
            " 7.8 backpacking of wandelen met een rugzak",
            " 7.3 heuvels beklimmen met een lading van 10 tot 20 pond.",
            " 8.3 heuvels beklimmen met een lading van 21 tot 42 pond.",
            " 9.0 heuvels beklimmen met een lading van 42+ pond.",
            " 5.3 wandelen op een normaal tempo door velden en heuvels",
            " 6.5 race wandelen",
            " 8.0 bergbeklimmen",
            " 2.0 wandelen, heel traag",
            " 3.5 wandelen voor plezier",
            " 3.0 de hond uitlaten",
            " 4.8 wandelen, als oefening, met snelheid van 3.5 tot 4 mph, met wandelstokken, Nordic wandelen aan een gemiddeld tempo",
            " 6.8 wandelen, als oefening, met wandelstokken, Nordic wandelen, bergop",
        };
    }

    @Override
    public String[] p_trim_modes() {
        return new String[] {
            "Grootte",
            "Grootte en ouderdom",
            "Ouderdom",
            "Grootte of ouderdom",
        };
    }

}