package ch.bailu.aat_lib.resources;

/**
    This file was autogenerated by 'aat-lib/util/generate_strings.py'.
*/
public class Strings_de extends Strings {
    @Override
    public String on() { return "An";}

    @Override
    public String off() { return "Aus";}

    @Override
    public String auto() { return "Auto";}

    @Override
    public String none() { return "Kein";}

    @Override
    public String enter() { return "Eingabe…";}

    @Override
    public String pick() { return "Auswählen (SAF)…";}

    @Override
    public String ok() { return "OK";}

    @Override
    public String cancel() { return "Abbrechen";}

    @Override
    public String gps_nogps() { return "Kein";}

    @Override
    public String gps_noaccess() { return "Verweigert";}

    @Override
    public String tracker_start() { return "Start";}

    @Override
    public String tracker_pause() { return "Pause";}

    @Override
    public String tracker_stop() { return "Stopp";}

    @Override
    public String tracker_resume() { return "Weiter";}

    @Override
    public String tracker_restore() { return "Track wiederherstellen";}

    @Override
    public String status_paused() { return "Pause";}

    @Override
    public String status_autopaused() { return "Autopause";}

    @Override
    public String intro_about() { return "Info";}

    @Override
    public String intro_documentation() { return "Dokumentation";}

    @Override
    public String intro_map() { return "Kartenansicht";}

    @Override
    public String intro_nominatim() { return "Suche in der Karte";}

    @Override
    public String intro_overlay_list() { return "Liste der Overlays";}

    @Override
    public String intro_list() { return "Aufgezeichnete Aktivitäten";}

    @Override
    public String intro_external_list() { return "Externe Dateien";}

    @Override
    public String intro_settings() { return "Einstellungen";}

    @Override
    public String label_summary() { return "Zusammenfassung";}

    @Override
    public String label_filter() { return "Filter";}

    @Override
    public String label_list() { return "Liste";}

    @Override
    public String filter_date_start() { return "Startdatum";}

    @Override
    public String filter_date_to() { return "Enddatum";}

    @Override
    public String filter_geo() { return "Innerhalb Bereich";}

    @Override
    public String query_save_copy() { return "Kopie speichern";}

    @Override
    public String p_general() { return "Allgemein";}

    @Override
    public String p_weight_title() { return "Gewicht in kg";}

    @Override
    public String p_unit_title() { return "Einheiten";}

    @Override
    public String p_preset_slots() { return "Anzahl Voreinstellungen";}

    @Override
    public String p_directory_data() { return "Interne Dateien";}

    @Override
    public String p_system() { return "System";}

    @Override
    public String p_location_provider() { return "Standortbestimmung durch…";}

    @Override
    public String p_post_autopause() { return "Postprocessed Autopause";}

    @Override
    public String p_cache_size() { return "Größe des internen Zwischenspeichers";}

    @Override
    public String p_fix_gps() { return "GPS-Zeit anpassen";}

    @Override
    public String p_legend_fulldistance() { return "Gesamtdistanz";}

    @Override
    public String p_overlay() { return "Overlays";}

    @Override
    public String p_preset() { return "Voreinstellungen";}

    @Override
    public String p_met() { return "MET und Name";}

    @Override
    public String p_accuracy_filter() { return "Genauigkeitsfilter";}

    @Override
    public String p_missing_trigger() { return "Auslöser für fehlendes Signal";}

    @Override
    public String p_distance_filter() { return "Distanz-Filter";}

    @Override
    public String p_autopause() { return "Autopause";}

    @Override
    public String p_tracker_autopause() { return "Tracking automatisch pausieren";}

    @Override
    public String p_backlight_title() { return "Bildschirm";}

    @Override
    public String p_backlight_off() { return "Systemeinstellung";}

    @Override
    public String p_backlight_on() { return "Immer an";}

    @Override
    public String p_backlight_on_no_lock() { return "Immer an (ohne Sperrbildschirm)";}

    @Override
    public String p_map() { return "Karte";}

    @Override
    public String p_mapsforge_directory() { return "Verzeichnis für Offline-Karten";}

    @Override
    public String p_enable_cache() { return "Zwischenspeichern";}

    @Override
    public String p_directory_tiles() { return "Zwischenspeicher für Kacheln";}

    @Override
    public String p_tile_size() { return "Kachelgrösse";}

    @Override
    public String p_tiles() { return "Karte";}

    @Override
    public String p_trim_cache() { return "Zwischenspeicher verkleinern";}

    @Override
    public String p_trim_mode() { return "Modus";}

    @Override
    public String p_trim_size() { return "Größe";}

    @Override
    public String p_trim_age() { return "Alter";}

    @Override
    public String p_trim_month() { return "Monat";}

    @Override
    public String p_trim_months() { return "Monate";}

    @Override
    public String p_trim_year() { return "Jahr";}

    @Override
    public String p_trim_years() { return "Jahre";}

    @Override
    public String p_trim_days() { return "Tage";}

    @Override
    public String p_trim_total() { return "Total";}

    @Override
    public String p_remove_all() { return "Zwischenspeicher löschen";}

    @Override
    public String p_remove_all_in() { return "Zwischenspeicher löschen in";}

    @Override
    public String p_remove_old() { return "Alte Kacheln löschen";}

    @Override
    public String p_remove_old_in() { return "Alte Kacheln löschen in";}

    @Override
    public String file_delete() { return "Datei löschen";}

    @Override
    public String file_delete_ask() { return "Datei löschen?";}

    @Override
    public String file_copy() { return "Kopieren nach…";}

    @Override
    public String file_exists() { return " ist bereits vorhanden!";}

    @Override
    public String file_overlay() { return "Als Overlay verwenden";}

    @Override
    public String file_reload() { return "Vorschau neu laden";}

    @Override
    public String file_rename() { return "Datei umbenenen";}

    @Override
    public String file_send() { return "Senden…";}

    @Override
    public String file_view() { return "Anzeigen/Bearbeiten…";}

    @Override
    public String file_is_writeable() { return ": lesen und schreiben.";}

    @Override
    public String file_is_writeonly() { return ": nur lesen.";}

    @Override
    public String file_is_readonly() { return ": nur lesen.";}

    @Override
    public String file_is_missing() { return "\u0020existiert nicht.";}

    @Override
    public String file_is_denied() { return ": kein Zugriff.";}

    @Override
    public String location_send() { return "Position senden…";}

    @Override
    public String location_view() { return "Position ansehen…";}

    @Override
    public String file_mock() { return "Für simulierten Standort verwenden";}

    @Override
    public String clipboard_copy() { return "\u21d2 Zwischenablage";}

    @Override
    public String clipboard_paste() { return "\u21d0 Zwischenablage";}

    @Override
    public String dialog_yes() { return "Ja";}

    @Override
    public String dialog_no() { return "Nein";}

    @Override
    public String dialog_cancel() { return "Abbrechen";}

    @Override
    public String dialog_discard() { return "Verwerfen";}

    @Override
    public String dialog_save() { return "Speichern";}

    @Override
    public String dialog_modified() { return "Datei wurde verändert";}

    @Override
    public String d_name() { return "Name";}

    @Override
    public String d_startdate() { return "Start";}

    @Override
    public String d_longitude() { return "Länge";}

    @Override
    public String d_latitude() { return "Breite";}

    @Override
    public String d_accuracy() { return "Genauigkeit";}

    @Override
    public String d_enddate() { return "Ende";}

    @Override
    public String d_acceleration() { return "Beschleunigung";}

    @Override
    public String d_bearing() { return "Lage";}

    @Override
    public String d_path() { return "Pfad";}

    @Override
    public String d_state() { return "Status";}

    @Override
    public String d_size() { return "Größe";}

    @Override
    public String d_ascend() { return "Anstieg";}

    @Override
    public String d_descend() { return "Abstieg";}

    @Override
    public String d_slope() { return "Steigung";}

    @Override
    public String pause() { return "Pause";}

    @Override
    public String pause_ap() { return "Pause (mit Autopause)";}

    @Override
    public String speed() { return "Geschwindigkeit";}

    @Override
    public String average() { return "Durchschnitt";}

    @Override
    public String average_ap() { return "Durchschnitt (ohne Pause)";}

    @Override
    public String maximum() { return "Maximum";}

    @Override
    public String distance() { return "Distanz";}

    @Override
    public String altitude() { return "Höhe";}

    @Override
    public String time() { return "Zeit";}

    @Override
    public String time_ap() { return "Zeit (ohne Pause)";}

    @Override
    public String calories() { return "Kalorien";}

    @Override
    public String tt_edit_add() { return "Am Ort in der Kartenmitte einen Punkt hinzufügen";}

    @Override
    public String tt_edit_remove() { return "Ausgewählten Punkt entfernen";}

    @Override
    public String tt_edit_up() { return "Ausgewählten Punkt in der Liste nach oben bewegen";}

    @Override
    public String tt_edit_down() { return "Ausgewählten Punkt in der Liste nach unten bewegen";}

    @Override
    public String tt_edit_redo() { return "Letzte rückgängig gemachte Aktion wiederherstellen";}

    @Override
    public String tt_edit_undo() { return "Letzte Aktion rückgängig machen";}

    @Override
    public String tt_info_grid() { return "Zwischen verschiedenen Kartengittern wechseln";}

    @Override
    public String tt_info_legend() { return "Zwischen Beschreibungsmodi wechseln";}

    @Override
    public String tt_info_nominatim() { return "Suchanfrage über OSM-Nominatim";}

    @Override
    public String tt_info_reload() { return "Sichtbare Kacheln neu laden";}

    @Override
    public String tt_map_zoomin() { return "Hineinzoomen";}

    @Override
    public String tt_map_zoomout() { return "Heraus zoomen";}

    @Override
    public String tt_map_home() { return "Karte im Bekannten Standort zentrieren";}

    @Override
    public String tt_map_frame() { return "Zwischen der Gesamtansicht der Overlays wechseln";}

    @Override
    public String tt_nominatim_query() { return "Anfrage starten…";}

    @Override
    public String tt_nominatim_clear() { return "Zeile löschen";}

    @Override
    public String tt_info_location() { return "Importieren/exportieren der Kartenmitte";}

    @Override
    public String tt_menu_file() { return "Menu für Dateioperationen anzeigen";}

    @Override
    public String tt_cockpit_a() { return "Vollbild";}

    @Override
    public String tt_cockpit_b() { return "Aufgeteilt";}

    @Override
    public String tt_p_preset_slots() { return "Anzahl Verzeichnisse und Voreinstellungen um Tracks zu organisieren.";}

    @Override
    public String error_integer() { return "Falsche Eingabe, es sind nur Zahlen erlaubt.\n\"%s\"";}

    @Override
    public String error_integer_positive() { return "Zahl muss zwischen 1 und 999 sein.";}

    @Override
    public String error_long() { return "Falsche Eingabe, es sind nur Zahlen erlaubt.\n\"%s\"";}

    @Override
    public String error_met() { return "Die erste Zahl muss zwischen 0.0 und 20.0 sein, gefolgt von einem Leerzeichen.";}

    @Override
    public String[] p_unit_list() {
        return new String[] {
            "Metrisch (km, km/h)",
            "Britisch (mi, mph)",
            "Nautisch (nm, kn)",
            "SI-Einheiten",
        };
    }

    @Override
    public String[] p_met_list() {
        return new String[] {
            " 6.8 Radfahren, mittlere Leistung",
            " 8.5 MTB, allgemein",
            " 7.0 Jogging, allgemein",
            " 6.0 Wandern, cross country",
            " 2.0 Test",
            "14.0 MTB, uphill",
            "16.0 MTB, Wettbewerb",
            " 5.8 Radfahren, wenig Leistung",
            "10.0 Radfahren, hohe Leistung",
            " 6.0 Rennen, langsam",
            " 9.0 Rennen, Querfeldein",
            " 9.8 Rennen, 6 mph (10 min/mile)",
            " 9.0 Rennen, Querfeldein (schnell)",
            "10.0 Rennen, auf der Bahn",
            " 8.0 running, training, pushing a wheelchair or baby carrier",
            "13.3 Rennen, Marathon",
            " 7.8 Wandern mit kleinem Rucksack",
            " 7.3 Klettern mit wenig Gepäck",
            " 8.3 Klettern mit mittlerem Gepäck",
            " 9.0 Klettern mit viel Gepäck",
            " 5.3 Wandern/Spazieren normale Geschwindigkeit",
            " 6.5 Wettkampf-Gehen",
            " 8.0 Bergsteigen/Klettern",
            " 2.0 Spazieren, sehr langsam",
            " 3.5 Spazieren, normal",
            " 3.0 Gassigehen",
            " 4.8 Spazieren/Nordic Walking mittelere Anstrengung",
            " 6.8 Spazieren/Nordic Walking hohe Anstrengung",
        };
    }

    @Override
    public String[] p_trim_modes() {
        return new String[] {
            "Größe",
            "Größe und alter",
            "Alter",
            "Größe oder alter",
        };
    }

}