package ch.bailu.aat_lib.resources;

/**
    This file was autogenerated by 'aat-lib/util/generate_strings.py'.
*/
public class Strings_cs extends Strings {
    @Override
    public String on() { return "Zap.";}

    @Override
    public String off() { return "Vyp.";}

    @Override
    public String auto() { return "Auto";}

    @Override
    public String none() { return "Žádný";}

    @Override
    public String enter() { return "Zadat…";}

    @Override
    public String pick() { return "Vybrat (SAF)…";}

    @Override
    public String ok() { return "OK";}

    @Override
    public String cancel() { return "Zrušit";}

    @Override
    public String gps() { return "GPS";}

    @Override
    public String gps_wait() { return "…";}

    @Override
    public String gps_nogps() { return "Ne";}

    @Override
    public String gps_noaccess() { return "Zakázáno";}

    @Override
    public String tracker() { return "Záznam";}

    @Override
    public String tracker_start() { return "Start";}

    @Override
    public String tracker_pause() { return "Pauza";}

    @Override
    public String tracker_stop() { return "Stop";}

    @Override
    public String tracker_resume() { return "Pokračovat";}

    @Override
    public String tracker_restore() { return "Obnovit záznam";}

    @Override
    public String status_paused() { return "Pozastaveno";}

    @Override
    public String status_autopaused() { return "Autopauza";}

    @Override
    public String intro_about() { return "O aplikaci";}

    @Override
    public String intro_readme() { return "README";}

    @Override
    public String intro_documentation() { return "Dokumentace";}

    @Override
    public String intro_cockpit_a() { return "Kokpit A";}

    @Override
    public String intro_cockpit_b() { return "Kokpit B";}

    @Override
    public String intro_map() { return "Mapa";}

    @Override
    public String intro_nominatim() { return "Vyhledávání v mapě";}

    @Override
    public String intro_overlay_list() { return "Překryvná data";}

    @Override
    public String intro_list() { return "Seznam aktivit";}

    @Override
    public String intro_external_list() { return "Externí soubory";}

    @Override
    public String intro_settings() { return "Možnosti";}

    @Override
    public String label_summary() { return "Přehled";}

    @Override
    public String label_filter() { return "Filtr";}

    @Override
    public String label_list() { return "Souhrn";}

    @Override
    public String filter_geo() { return "Vnitřní hranice";}

    @Override
    public String filter_date_start() { return "Počáteční datum";}

    @Override
    public String filter_date_to() { return "Koncové datum";}

    @Override
    public String query_overpass() { return "Overpass";}

    @Override
    public String query_features() { return "Fuknce OSM";}

    @Override
    public String query_save_copy() { return "Uložit kopii";}

    @Override
    public String p_general() { return "Hlavní";}

    @Override
    public String p_post_autopause() { return "Automatická pauza při následném zpracování";}

    @Override
    public String p_preset_slots() { return "Předvolené obrazovky";}

    @Override
    public String p_unit_title() { return "Jednotky";}

    @Override
    public String p_location_provider() { return "Poskytovatel polohy";}

    @Override
    public String p_location_gps() { return "Systém GPS";}

    @Override
    public String p_location_mock() { return "Simulovaná poloha";}

    @Override
    public String p_directory_data() { return "Složka s daty";}

    @Override
    public String p_cache_size() { return "Velikost dočasné interní paměti";}

    @Override
    public String p_fix_gps() { return "Opravit čas GPS";}

    @Override
    public String p_overlay() { return "Překryvné vrstvy";}

    @Override
    public String p_legend_fulldistance() { return "Distance continuous";}

    @Override
    public String p_preset() { return "Aktivita";}

    @Override
    public String p_met() { return "MET a jméno";}

    @Override
    public String p_autopause() { return "Autopauza";}

    @Override
    public String p_tracker_autopause() { return "Nastavit automatickou pauzu záznamu";}

    @Override
    public String p_weight_title() { return "Vaše váha v kg";}

    @Override
    public String p_backlight_title() { return "Podsvícení";}

    @Override
    public String p_backlight_off() { return "Výchozí nastavení";}

    @Override
    public String p_backlight_on() { return "Ponechat zapnuté";}

    @Override
    public String p_backlight_on_no_lock() { return "Ponechat zapnuté (zrušit zámek displeje)";}

    @Override
    public String p_system() { return "Systém";}

    @Override
    public String p_tile_size() { return "Velikost dlaždice";}

    @Override
    public String p_accuracy_filter() { return "Filtr přesnosti";}

    @Override
    public String p_distance_filter() { return "Filtr vzdálenosti";}

    @Override
    public String p_missing_trigger() { return "Missing trigger";}

    @Override
    public String p_map() { return "Mapa";}

    @Override
    public String p_mapsforge_directory() { return "Adresář pro offline mapy";}

    @Override
    public String p_mapsforge_theme() { return "Vzhled offline map";}

    @Override
    public String p_enable_cache() { return "Povolit dočasné úložiště";}

    @Override
    public String p_directory_tiles() { return "Dočasný adresář pro dlaždice";}

    @Override
    public String p_trim_cache() { return "Zmenšit velikost dočasného úložiště";}

    @Override
    public String p_tiles() { return "Mapové dlaždice";}

    @Override
    public String p_trim_mode() { return "Způsob redukce";}

    @Override
    public String p_trim_size() { return "Zmenšit podle velikosti";}

    @Override
    public String p_trim_age() { return "Zmenšit podle data";}

    @Override
    public String p_trim_month() { return "Měsíc";}

    @Override
    public String p_trim_months() { return "Měsíců";}

    @Override
    public String p_trim_year() { return "Rok";}

    @Override
    public String p_trim_years() { return "Let";}

    @Override
    public String p_trim_days() { return "Dnů";}

    @Override
    public String p_trim_total() { return "Celkem";}

    @Override
    public String p_remove_all() { return "Vymazat celé dočasné úložiště";}

    @Override
    public String p_remove_all_in() { return "Vymazat celé dočasné úložiště z ";}

    @Override
    public String p_remove_old() { return "Smazat staré dlaždice";}

    @Override
    public String p_remove_old_in() { return "Smazat staré dlaždice z ";}

    @Override
    public String file_reload() { return "Obnovit náhled";}

    @Override
    public String file_delete() { return "Odstranit soubor";}

    @Override
    public String file_rename() { return "Přejmenovat soubor";}

    @Override
    public String file_overlay() { return "Použít překrytí";}

    @Override
    public String file_mock() { return "Použít simulovanou polohu";}

    @Override
    public String file_delete_ask() { return "Odstranit soubor?";}

    @Override
    public String file_send() { return "Odeslat…";}

    @Override
    public String file_view() { return "Zobrazit/Editovat…";}

    @Override
    public String file_copy() { return "Kopírovat do…";}

    @Override
    public String file_exists() { return "\u0020již existuje!";}

    @Override
    public String file_is_writeable() { return "\u0020je zapisovatelný.";}

    @Override
    public String file_is_writeonly() { return "\u0020je pouze k zápisu.";}

    @Override
    public String file_is_readonly() { return "\u0020je pouze ke čtení.";}

    @Override
    public String file_is_missing() { return "\u0020neexistuje.";}

    @Override
    public String file_is_denied() { return "\u0020není dostupný.";}

    @Override
    public String location_title() { return "Vycentrolvat pozici";}

    @Override
    public String location_view() { return "Zobrazit pozici…";}

    @Override
    public String location_send() { return "Odeslat pozici…";}

    @Override
    public String clipboard_copy() { return "\u21d2 Schránka";}

    @Override
    public String clipboard_paste() { return "\u21d0 Schránka";}

    @Override
    public String dialog_yes() { return "Ano";}

    @Override
    public String dialog_no() { return "Ne";}

    @Override
    public String dialog_cancel() { return "Zrušit";}

    @Override
    public String dialog_discard() { return "Vyřadit";}

    @Override
    public String dialog_save() { return "Uložit";}

    @Override
    public String dialog_modified() { return "Soubor byl upraven";}

    @Override
    public String d_longitude() { return "Délka";}

    @Override
    public String d_latitude() { return "Šířka";}

    @Override
    public String d_name() { return "Název";}

    @Override
    public String d_accuracy() { return "Přesnost";}

    @Override
    public String d_enddate() { return "Konec";}

    @Override
    public String d_startdate() { return "Začátek";}

    @Override
    public String d_acceleration() { return "Zrychlení";}

    @Override
    public String d_bearing() { return "Azimut";}

    @Override
    public String d_path() { return "Cesta";}

    @Override
    public String d_state() { return "Stav";}

    @Override
    public String d_size() { return "Velikost";}

    @Override
    public String d_ascend() { return "Stoupání";}

    @Override
    public String d_descend() { return "Klesání";}

    @Override
    public String d_slope() { return "Sklon";}

    @Override
    public String pause() { return "Pauza";}

    @Override
    public String pause_ap() { return "Pauza (s autopauzou)";}

    @Override
    public String speed() { return "Rychlost";}

    @Override
    public String average() { return "Průměr";}

    @Override
    public String average_ap() { return "Průměr (bez pauz)";}

    @Override
    public String maximum() { return "Maximum";}

    @Override
    public String distance() { return "Vzdálenost";}

    @Override
    public String altitude() { return "Výška";}

    @Override
    public String time() { return "Celkový čas";}

    @Override
    public String time_ap() { return "Celkový čas (bez pauz)";}

    @Override
    public String calories() { return "Kalorie";}

    @Override
    public String name() { return "Název";}

    @Override
    public String tt_edit_add() { return "Přidat bod podle středu mapy.";}

    @Override
    public String tt_edit_remove() { return "Odstranit vybraný bod.";}

    @Override
    public String tt_edit_up() { return "Posunout bod v pořadí dolu.";}

    @Override
    public String tt_edit_down() { return "Posunout bod v pořadi nahoru.";}

    @Override
    public String tt_edit_redo() { return "Vzít zpět posledně vrácenou akci..";}

    @Override
    public String tt_edit_undo() { return "Vrátit poslední akci.";}

    @Override
    public String tt_info_grid() { return "Přepnout mezi režimy mřížky.";}

    @Override
    public String tt_info_legend() { return "Přepnout mezi režimy popisku záznamu.";}

    @Override
    public String tt_info_nominatim() { return "Hledat pomocí OSM-Nominatim.";}

    @Override
    public String tt_info_reload() { return "Přenačíst viditelné dlaždice.";}

    @Override
    public String tt_info_location() { return "Import/export of center location.";}

    @Override
    public String tt_map_zoomin() { return "Přiblížit mapu.";}

    @Override
    public String tt_map_zoomout() { return "Oddálit mapu.";}

    @Override
    public String tt_map_home() { return "Uzamknout střed mapy podle aktuální polohy.";}

    @Override
    public String tt_map_frame() { return "Switch between GPX-Overlays and frame them.";}

    @Override
    public String tt_nominatim_query() { return "Vyhledat.";}

    @Override
    public String tt_nominatim_clear() { return "Smazat řádek v hledaném textu.";}

    @Override
    public String tt_cockpit_a() { return "Celá obrazovka";}

    @Override
    public String tt_cockpit_b() { return "Rozdělená obrazovka";}

    @Override
    public String tt_menu_file() { return "Zobrazit volby práce se soubory.";}

    @Override
    public String tt_p_preset_slots() { return "Počet adresářů a obrazovek, které chcete použít pro správu záznamů.";}

    @Override
    public String error_integer() { return "Nesprávný vstup, povolena jsou pouze celá čísla.\n\"%s\"";}

    @Override
    public String error_integer_positive() { return "Váha musí být mezi 1 a 999.";}

    @Override
    public String error_long() { return "Nesprávný vstup, povolena jsou pouze.\n\"%s\"";}

    @Override
    public String error_met() { return "První číslo musí být mezi 0.0 a 20.0 s mezerou na konci.";}

    @Override
    public String[] p_unit_list() {
        return new String[] {
            "Metrické (km, km/h)",
            "Imperiální (mi, mph)",
            "Námořní (nm, kn)",
            "Mezinárodní systém jednotek",
        };
    }

    @Override
    public String[] p_met_list() {
        return new String[] {
            " 6.8 cyklistika, volnočasová, mírná zátěž",
            " 8.5 cyklistika, horská, obecné",
            " 7.0 běh, obecné",
            " 6.0 pěší turistika, terénní",
            " 2.0 test",
            "14.0 cyklistika, horská, do kopce",
            "16.0 cyklistika, horská, závodní",
            " 5.8 cyklistika, volnočasová, mírná zátěž",
            "10.0 cyklistika, závod nebo volnočasová, velká zátěž",
            " 6.0 běh, 4 mph (13 min/míli)",
            " 9.0 běh, 5.2 mph (11.5 min/míli)",
            " 9.8 běh, 6 mph (10 min/míli)",
            " 9.0 běh, terénní",
            "10.0 běh, na trati, týmový výcvik",
            " 8.0 běh, trénink, tlačení invalidního vozíku nebo kočárku",
            "13.3 běh, maraton",
            " 7.8 túra, pěší turistika nebo organizovaná chůze s batohem",
            " 7.3 horozelecký výstup s nákladem od 4,5 kg do 9 kg",
            " 8.3 horozelecký výstup s nákladem od 9,5 kg do 19 kg",
            " 9.0 horozelecký výstup s nákladem na 19 kg",
            " 5.3 pěší turistika nebo chůze běžnou rychlostí přes pole a svahy",
            " 6.5 sportovní chůze",
            " 8.0 horolezectví",
            " 2.0 chůze, procházka, velmi pomalá",
            " 3.5 chůze pro radost",
            " 3.0 vycházka se psem",
            " 4.8 chůze, pro trénink, od 5,6 km/h do 6,4 km/h, s lyžařskými holemi, severská chůze, vyrovnaná, mírné tempo",
            " 6.8 chůze, pro trénink, s lyžařskými holemi, severská chůze, do kopce",
        };
    }

    @Override
    public String[] p_trim_modes() {
        return new String[] {
            "Velikost",
            "Velikost a stáří",
            "Stáří",
            "Velikost nebo stáří",
        };
    }

}