name: Build on ubuntu

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Build with Gradle
      run: ./gradlew build

    - name: Collect files for distribution
      run: ci/collect-artifacts.sh

    - name: Upload artifacts (gtk)
      uses: actions/upload-artifact@v2
      with:
        name: aat-gtk
        path: dist/gtk
        if-no-files-found: error

    - name: Upload artifacts (android)
      uses: actions/upload-artifact@v2
      with:
        name: aat-android
        path: dist/android
        if-no-files-found: error
